global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'website-analyzer-api'
    static_configs:
      - targets: ['website-analyzer-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Monitor system metrics if node_exporter is added
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node-exporter:9100']